version: '3'

services:
  
  build_container:
    container_name: build_container
    image: jupytercloud-project/build-container:latest
    ports:
    - "127.0.0.1:6000-6020:6000-6020"
    volumes:
    - .:/src
    - ./packer_cache:/packer_cache
    - ./qemu-registry:/qemu-registry
    command: /bin/bash /src/tools/hashicorp/packer/images/openstack-alpine-image/build.bash

  publish_container:
    container_name: publish_container
    image: jupytercloud-project/build-container:latest
    volumes:
    - ./qemu-registry:/qemu-registry
    environment:
    - GITHUB_TOKEN=${GITHUB_TOKEN}
    - CIRCLE_PROJECT_USERNAME=${CIRCLE_PROJECT_USERNAME}
    - CIRCLE_PROJECT_REPONAME=${CIRCLE_PROJECT_REPONAME}
    - CIRCLE_SHA1=${CIRCLE_SHA1}
    - RELEASE_VERSION=${RELEASE_VERSION}
    - ARTIFACT_DIR='/qemu-registry'
    command: |
      ghr -t ${GITHUB_TOKEN} \
          -u ${CIRCLE_PROJECT_USERNAME} \
          -r ${CIRCLE_PROJECT_REPONAME} \
          -c ${CIRCLE_SHA1} \
          -delete \
          ${RELEASE_VERSION} \
          ${ARTIFACT_DIR}/
